GET http://localhost:5000

###
POST http://localhost:5000/register
Content-Type: application/json
    
{
    "name": "John rocker",
    "email": "johnrocker@gmail.com",
    "password": "password",
    "confirm_password": "password"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "johnrocker@gmail.com",
    "password": "password"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout

### Nutrisions!
GET http://localhost:5000/nutrisions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm5hbWUiOiJKb2huIGRvc2UiLCJlbWFpbCI6ImpvaG5kb3NlQGdtYWlsLmNvbSIsImlhdCI6MTcwMTcxNjAyMCwiZXhwIjoxNzAxODAyNDIwfQ.VJA8fcffDwxqVI2WfDCjTk_2lcMpF2_O5fUZP3WVJdQ

###
POST http://localhost:5000/nutrisions
Content-Type: application/json

{
    "nutrisionId": "nasi_putih",
    "name": "Nasi Putih",
    "calories": "112",
    "carbs": "222",
    "proteins": "12",
    "carbs": "511",
    "fats": "23",
    "minerals": "12"
}


###
POST http://localhost:5000/addmeal/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJKb2huIHJvY2tlciIsImVtYWlsIjoiam9obnJvY2tlckBnbWFpbC5jb20iLCJpYXQiOjE3MDI0ODk5OTYsImV4cCI6MTcwMjU3NjM5Nn0.qWr0NIBs7LP5o4GmrM7LRaeOYxBv9v6ihcxFewSosm8
Content-Type: application/json

{
    "meals_name": ["kacang"]
}


### delete meals
POST http://localhost:5000/deletemeal/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJKb2huIHRpdGl0IiwiZW1haWwiOiJqb2hudGl0aXRAZ21haWwuY29tIiwiaWF0IjoxNzAxOTExOTkwLCJleHAiOjE3MDE5OTgzOTB9.peg0qAZ7umjQ3m_uoyrDn29m0qZfdI_YwFpKZ_6MOHQ
Content-Type: application/json

{
    "mealId" : 2
}
### Random Facts!
GET http://localhost:5000/facthealths

###
POST http://localhost:5000/facthealths
Content-Type: application/json

{
    "fact": "Regular Health Check-ups are Essential: Regular medical check-ups and screenings can help detect potential health issues early, allowing for timely intervention and prevention.",
    "source": "https://www.heart.org/en/health-topics/consumer-healthcare/doctor-appointments-questions-to-ask-your-doctor"
}

###
POST http://localhost:5000/forgotpassword
Content-Type: application/json

{
    "email": "johnjay@gmail.com"
}

###
GET http://localhost:5000/dashboard/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsIm5hbWUiOiJKb2huIHJvY2tlciIsImVtYWlsIjoiam9obnJvY2tlckBnbWFpbC5jb20iLCJpYXQiOjE3MDIwMjI5MjcsImV4cCI6MTcwMjEwOTMyN30.u3BGoASj8kB1LG1y4I71JXWK259z0nYAc9haRy1phKc


### Meals!
GET http://localhost:5000/meals/1


### Change Password
POST http://localhost:5000/changepassword/2
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJKb2huIHRpdGl0IiwiZW1haWwiOiJqb2hudGl0aXRAZ21haWwuY29tIiwiaWF0IjoxNzAxOTExOTkwLCJleHAiOjE3MDE5OTgzOTB9.peg0qAZ7umjQ3m_uoyrDn29m0qZfdI_YwFpKZ_6MOHQ

{
    "oldPassword": "password",
    "newPassword": "password1",
    "confirmNewPassword": "password1"
}

### Update Profile
PUT http://localhost:5000/updateprofile/1
content-type: application/json

{
    "name": "John hebat",
    "age" : "22",
    "gender":"L"
}