GET http://localhost:5000

###
POST http://localhost:5000/register
Content-Type: application/json
    
{
    "name": "John awan",
    "email": "johnawan@gmail.com",
    "password": "password",
    "confirm_password": "password"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "johndose@gmail.com",
    "password": "password"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout

### Nutrisions!
GET http://localhost:5000/nutrisions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm5hbWUiOiJKb2huIGRvc2UiLCJlbWFpbCI6ImpvaG5kb3NlQGdtYWlsLmNvbSIsImlhdCI6MTcwMTcxNjAyMCwiZXhwIjoxNzAxODAyNDIwfQ.VJA8fcffDwxqVI2WfDCjTk_2lcMpF2_O5fUZP3WVJdQ

###
POST http://localhost:5000/nutrisions
Content-Type: application/json

{
    "name" : "Mango",
    "description" : "Mango is rich in vitamins, minerals, and antioxidants, and it has been associated with many health benefits, including potential anticancer effects, as well as improved immunity and digestive and eye health"
}

### Meals!
GET http://localhost:5000/meals/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWUiOiJKb2huIFNpbnMiLCJlbWFpbCI6ImpvaG5zaW5zQGdtYWlsLmNvbSIsImlhdCI6MTcwMDQ5MTE0NywiZXhwIjoxNzAwNDkxMTc3fQ.8qWYoMii6jPPRdnRYX8lJVzGG9wF5zUW7k99CA_KSMI

###
POST http://localhost:5000/addmeal/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm5hbWUiOiJKb2huIGRvc2UiLCJlbWFpbCI6ImpvaG5kb3NlQGdtYWlsLmNvbSIsImlhdCI6MTcwMTcxNjAyMCwiZXhwIjoxNzAxODAyNDIwfQ.VJA8fcffDwxqVI2WfDCjTk_2lcMpF2_O5fUZP3WVJdQ
Content-Type: application/json


{
    "meals_name" : "Mie Tek tek",
    "calories": "222",
    "proteins": "22",
    "carbs": "22",
    "fats": "22",
    "minerals": "22"
}

### delete meals
POST http://localhost:5000/deletemeal/1
Content-Type: application/json

{
    "mealId" : "6"
}
### Random Facts!
GET http://localhost:5000/facthealths

###
POST http://localhost:5000/facthealths
Content-Type: application/json

{
    "fact": "Regular Health Check-ups are Essential: Regular medical check-ups and screenings can help detect potential health issues early, allowing for timely intervention and prevention.",
    "source": "https://www.heart.org/en/health-topics/consumer-healthcare/doctor-appointments-questions-to-ask-your-doctor"
}

###
POST http://localhost:5000/forgotpassword
Content-Type: application/json

{
    "email": "johnjay@gmail.com"
}

###
GET http://localhost:5000/meals/calculate/1