GET http://localhost:5000

###
POST http://localhost:5000/register
Content-Type: application/json
    
{
    "name": "John rocker",
    "email": "johnrocker@gmail.com",
    "password": "password",
    "confirm_password": "password"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "johnrocker@gmail.com",
    "password": "password"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout

### Nutrisions!
GET http://localhost:5000/nutrisions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm5hbWUiOiJKb2huIGRvc2UiLCJlbWFpbCI6ImpvaG5kb3NlQGdtYWlsLmNvbSIsImlhdCI6MTcwMTcxNjAyMCwiZXhwIjoxNzAxODAyNDIwfQ.VJA8fcffDwxqVI2WfDCjTk_2lcMpF2_O5fUZP3WVJdQ

###
POST http://localhost:5000/nutrisions
Content-Type: application/json

{
    "nutrisionId": "pisang",
    "name": "Pisang",
    "calories": "108",
    "carbs": "24",
    "proteins": "1",
    "fats": "1",
    "minerals": "0"
}


###
POST http://localhost:5000/addmeal/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJKb2huIHJvY2tlciIsImVtYWlsIjoiam9obnJvY2tlckBnbWFpbC5jb20iLCJpYXQiOjE3MDI1ODQ5NTIsImV4cCI6MTcwMjY3MTM1Mn0.PC4l4jk-eDgLUv3-5QxXXs8--YTlJb1ZFeI5jUxnNog
Content-Type: application/json

{
    "meals_name": ["nasi-putih","telur-putih","pisang"]
}


### delete meals
POST http://localhost:5000/deletemeal/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJKb2huIHRpdGl0IiwiZW1haWwiOiJqb2hudGl0aXRAZ21haWwuY29tIiwiaWF0IjoxNzAxOTExOTkwLCJleHAiOjE3MDE5OTgzOTB9.peg0qAZ7umjQ3m_uoyrDn29m0qZfdI_YwFpKZ_6MOHQ
Content-Type: application/json

{
    "mealId" : 2
}
### Random Facts!
GET http://localhost:5000/facthealths

###
POST http://localhost:5000/facthealths
Content-Type: application/json

{
    "fact": "Regular Health Check-ups are Essential: Regular medical check-ups and screenings can help detect potential health issues early, allowing for timely intervention and prevention.",
    "source": "https://www.heart.org/en/health-topics/consumer-healthcare/doctor-appointments-questions-to-ask-your-doctor"
}

###
POST http://localhost:5000/forgotpassword
Content-Type: application/json

{
    "email": "johnjay@gmail.com"
}

### Meals!
GET http://localhost:5000/meals/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJKb2huIHJvY2tlciIsImVtYWlsIjoiam9obnJvY2tlckBnbWFpbC5jb20iLCJpYXQiOjE3MDI0OTMyMDgsImV4cCI6MTcwMjU3OTYwOH0.HqPxwn3bn_jCecwIvggrNlikNPmXp4WzBtVcv7hybXo


### Change Password
POST http://localhost:5000/changepassword/2
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJKb2huIHRpdGl0IiwiZW1haWwiOiJqb2hudGl0aXRAZ21haWwuY29tIiwiaWF0IjoxNzAxOTExOTkwLCJleHAiOjE3MDE5OTgzOTB9.peg0qAZ7umjQ3m_uoyrDn29m0qZfdI_YwFpKZ_6MOHQ

{
    "oldPassword": "password",
    "newPassword": "password1",
    "confirmNewPassword": "password1"
}

### Update Profile
PUT http://localhost:5000/updateprofile/1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJKb2huIHJvY2tlciIsImVtYWlsIjoiam9obnJvY2tlckBnbWFpbC5jb20iLCJpYXQiOjE3MDI1ODQ5NTIsImV4cCI6MTcwMjY3MTM1Mn0.PC4l4jk-eDgLUv3-5QxXXs8--YTlJb1ZFeI5jUxnNog

{
    "name": "John hebat",
    "age" : "22",
    "gender":"L"
}


### checkdailycalories
GET http://localhost:5000/checkdailycalories/1

###
GET http://localhost:5000/dashboard/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJKb2huIHJvY2tlciIsImVtYWlsIjoiam9obnJvY2tlckBnbWFpbC5jb20iLCJpYXQiOjE3MDI1ODQ5NTIsImV4cCI6MTcwMjY3MTM1Mn0.PC4l4jk-eDgLUv3-5QxXXs8--YTlJb1ZFeI5jUxnNog
